from datetime import datetime
from enum import Enum
from pathlib import Path
from unittest.mock import Mock, patch

from pydantic import Field, SecretBytes, SecretStr, field_serializer
from pydantic_settings import BaseSettings, SettingsConfigDict
from typer.testing import CliRunner

from sync_settings_dotenv.main import app

runner = CliRunner()
TEST_MODULE = __name__


class ENV(Enum):
    dev = "DeV"
    ProD = "prod"


class DummySettings(BaseSettings):
    model_config = SettingsConfigDict(env_file="tests/.env")
    required: str
    foo: str = "bar"
    baz: int = 42
    env: ENV = ENV.dev
    dt: datetime = datetime(2022, 3, 30, 4, 34, 0)
    list_values: list[str] = Field(default_factory=lambda: ["1", "2", "3"])
    null_value: str | None = None
    excluded_field: str = Field(default="should not appear", exclude=True)
    boolean: bool = True
    secret_bytes: SecretBytes = SecretBytes(b"supersecret")
    secret_str: SecretStr

    @field_serializer("dt")
    def serialize_dt(self, dt: datetime) -> str:
        return dt.strftime("%Y-%m-%dT%H:%M:%SZZZ")

    @classmethod
    def assert_env_content(cls, content: str, include_header: bool = True):
        assert bool("# Generated by sync-settings-dotenv" in content) == include_header
        assert "REQUIRED=<required>\n" in content
        assert "FOO=bar\n" in content
        assert "BAZ=42\n" in content
        assert "ENV=DeV\n" in content
        assert "DT=2022-03-30T04:34:00ZZZ\n" in content
        assert "LIST_VALUES=['1', '2', '3']\n" in content
        assert "NULL_VALUE=None\n" in content
        assert "BOOLEAN=True\n" in content
        assert "SECRET_BYTES=supersecret\n" in content
        assert "SECRET_STR=<required>\n" in content

        assert "EXCLUDED_FIELD" not in content


@patch("sync_settings_dotenv.utils.shutil.copy")
def test_sync_settings_dotenv(mock_shutil: Mock, tmp_path: Path):
    env_path = tmp_path / ".env"
    input_params = [TEST_MODULE, env_path.as_posix()]
    result = runner.invoke(app, input_params)
    assert result.exit_code == 0
    content = env_path.read_text()
    DummySettings.assert_env_content(content)

    # Call again without any changes; no overwrite should happen
    input_params = [TEST_MODULE, env_path.as_posix(), "--overwrite-values", "--exact"]
    runner.invoke(app, input_params)
    mock_shutil.assert_not_called()
    new_content = env_path.read_text()
    assert new_content == content


@patch("sync_settings_dotenv.utils.shutil.copy")
def test_sync_settings_dotenv_no_header(mock_shutil: Mock, tmp_path: Path):
    env_path = tmp_path / ".env"
    runner.invoke(app, [TEST_MODULE, env_path.as_posix(), "--no-header"])
    content = env_path.read_text()
    mock_shutil.assert_not_called()
    DummySettings.assert_env_content(content, include_header=False)
